# Generated by Django 4.2.3 on 2026-02-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineTuningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fine-tuned Model', max_length=200)),
                ('base_model', models.CharField(max_length=200)),
                ('fine_tuned_model', models.CharField(blank=True, max_length=200)),
                ('epochs', models.IntegerField(default=3)),
                ('learning_rate', models.FloatField(default=0.0001)),
                ('batch_size', models.IntegerField(default=4)),
                ('dataset_file', models.CharField(blank=True, max_length=500)),
                ('dataset_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_epoch', models.IntegerField(default=0)),
                ('current_step', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='console_fin_created_802ec7_idx'), models.Index(fields=['status'], name='console_fin_status_ea3df8_idx'), models.Index(fields=['base_model'], name='console_fin_base_mo_543ffd_idx')],
            },
        ),
    ]
